### ISSUE TITLE
How to accept any data entered?

### ISSUE THREAD

**Issue by Abdullah0991** [avallete/ag-grid-autocomplete-editor#14]
Hi, thanks for the awesome lib.

How can I make the grid field accept any value, not just the items included in the 'selectData' param ?

**Comment by avallete** [comment]
Hi,

I'm not sure to totally understand your question. Is it about how you can change the 'selectData' after instanciation or about the `DataFormat` type in typescript.

If it's the first:

As described into the documentation, the 'selectData' parameter will be used if you already have the list of possible select options at the component instanciation. Or a default list.

If you need later on to fetch some other data, you should provide a 'fetch' function under the 'autocomplete' field. That way you should be able to get back data using a function to replace the actual selectData.

If it's the second:

I may change the default DataFormat to allow 'value' to be an 'any' type to be more generic that's true. In the meantime, you can totally pass object or whatever you want to the value and simply ignore the Typescript warning who will pop.

**Comment by Abdullah0991** [comment]
Hey,
First, English is not my native language so I am sorry. I will try to simplify my question:
I have a field called 'key', when user start type new key, I want to allow him either select an existing key or type new key not existed.
But as I saw in the demo if I type a word not existing in the 'selectData' parameter it will be ignored and the field will have empty value.

I think the question is clear enough now?

**Comment by avallete** [comment]
Hi,

Not my native language either, I use it only to code and watch GOT :yum:

I think I better understand your request here, I made two examples (here)[https://stackblitz.com/edit/ag-grid-autocomplete-editor-issue-14] of 'select with free fields addition' one for local data, other one for sever retrieved data, leveraging the 'fetch' and the 'onSelect' options of the component.

Please tell me if it solve your issue. If it does, I will probably add theses examples on the main Demo code.

**Comment by Abdullah0991** [comment]
Hi,
I don't want to push the new key to the data-source, I just want to allow user type anything even if not exist in the data-source.
The requested scenario is:- user will start typing in the field, the autocomplete package will give him the existing keys which match what he typed, if he want to choose an existing key he will use the autocomplete suggestions, if he want to type a new key (not exist) he can ignore the autocomplete suggestions and leave the field.

Thanks for you time.

**Comment by avallete** [comment]
> Hi,
> I don't want to push the new key to the data-source, I just want to allow user type anything even if not exist in the data-source.
> The requested scenario is:- user will start typing in the field, the autocomplete package will give him the existing keys which match what he typed, if he want to choose an existing key he will use the autocomplete suggestions, if he want to type a new key (not exist) he can ignore the autocomplete suggestions and complete typing then leave the field.
> 
> Thanks for you time.

In that case, the examples I provided will also work. 

You can simply remove the `onSelect` to let the default behavior. In that case, the value will be created on the fly when the user is typing whatever he want.

And without the `onSelect` overriding, when the 'enter' key will be hit, the value will properly be assigned and not saved in the data-source.

**Comment by Abdullah0991** [comment]
Great, but still a little problem:
The user has to hit `Enter` to accept the new value, but if he press `Tab` or just click with mouse in another row/field the new value will ignored.

How can I make the field accept the new value if the user leaves the field not just by hitting `Enter` key?

**Comment by avallete** [comment]
Well you'll probably need to extends the actual `AutocompleteSelectCellEditor` since it has not be designed to handle this special case.

You will probably end-up adding an eventListener on the eInput DOMElement who will set the currentItem to the actual input value when a change occurs.

Look kind of dirty but I doesn't have other ideas right now. If you find a way to do it with a clean method with a possibility to add this behavior as an option, feel free to submit a PR.
