### ISSUE TITLE
[feature request] Allow free text data

### ISSUE THREAD

**Issue by avallete** [avallete/ag-grid-autocomplete-editor#16]
Related to #14 #15

This issue is here to be an open discussion to talk about this feature request. 

# Feature Request:

## Desired Behavior:

Allow the user to not be limited by the select fields, and allow him to type free text instead.

## Technical implementation:

This options would be handled by a new parameter: `strict: bool = true`. By default it will be true, and if set to false, it will activate the 'allow free text' behavior.

Change the behavior who are doing the 'autoselection of the first item element' to put is as an parameter option: `autoselectfirst: bool = true`. This will allow, with the free text option, to choose if you want to enable 'free text' only when no other items are available. Or if you want to use it even if items are available eg:

```
data = ['toto', 'titi', 'tata']
userType: 't' => autocomplete will select the first element starting with t into the list, here 'toto'. But the user may just want to input 't' and validate with Enter, without selection an option.
```

It would be nice to also have another parameters who will be a function: `freeTextEntered: (cellEditor: AutocompleteSelectCellEditor, item: T)`

Who will be triggered when a non-select option is entered. Allowing to for instance, add this new option to the list of the already available ones. Or to perform a 'post' request to create a new item on the server side, ...

## Problematic to consider:

1. Since a select field is not only used to do 'input text' selection, and that I don't want to have many different return types. I think the better is to format the 'new typed text' as an option like another who will look like: `{value: inputText, label: inputText}`. I think it is the better option, do you see any downside on it ?

Please, be free to comment and say what do you think about the proposed changes. 

I will try to get some free time this weekend to implement theses new options.

**Comment by janhesters** [comment]
I had a busy weekend and only now had the possibility to read this. But I like the API with `strict` and `autoSelectFirst`. As soon as you publish this on NPM I will try it out. Thank you again for this great library. With this free text feature, it saves me a lot of work 🙏🏻

**Comment by avallete** [comment]
New version has been uploaded on npm (v.1.0.11).
