### ISSUE TITLE
Over writing params.data[key]

### ISSUE THREAD

**Issue by bgovi** [avallete/ag-grid-autocomplete-editor#22]
Hey thanks for working on this component. It seems pretty good. I noticed several of ag-grids built in features expects params.data[key] to return a value. It looks like this has been over written with an object that has value and label. This seems to be fine for the autocomplete but causes issues for many of the ag-grid functions. Is it possible to create another object in params such as params.autocomplete = {'value' :'xxx','label':1} and then store that value into params.data[key].

**Comment by avallete** [comment]
Hi,

Not sure to totally understand your question here.

By default, the autocomlete-editor component will always return the current selected item to the ag-grid. So, usually something looking like : `value: any, label: string`.

If you want to select some element of your data after that, did you try to use the [getters/formatters](https://www.ag-grid.com/javascript-grid-value-getters/) of ag-grid ?

**Comment by bgovi** [comment]
I will try this. 

Thanks.

**Comment by avallete** [comment]
In the mean time, I close the issue.

Feel free to reopen.
