### ISSUE TITLE
Interent Explorer support?

### ISSUE THREAD

**Issue by bgovi** [avallete/ag-grid-autocomplete-editor#31]
I checked the autocomplete package and their demo works on internet explorer. Put the ag-grid autocomplete drop down does not work.

**Comment by bgovi** [comment]
It seems that on live 105 of the typescript itemElement.append(fieldItem) is the issue.

From my googling append is a javascript function that is not supported by IE. However appendChild is a dom function that is supported by all browsers.

so I believe swapping 105 to itemElement.appendChild(fieldItem) should be fully compatible.

**Comment by avallete** [comment]
IE is not really targeted to be maintained by this library.

I will try to fix this when I found a machine running with Windows to test if the change really fix the issue.

**Comment by avallete** [comment]
Post mortem:

I applied the fix since it doesn't change the behavior on Chrome or Firefox anyway. But still didn't try it to IE. If you can test the new version `1.2.3` and tell me if it fix the issue, I will close it.

**Comment by bgovi** [comment]
It works on Internet Explorer and Edge. Thanks. Also. I am still learning a lot, I was wandering if you are interested in some paid Question and Answer sessions through a gchat or some video conference. Let me know. bgovi@umich.edu

**Comment by avallete** [comment]
Thank you for your feedback. I close the issue then.

I'll get in touch with you ;)
