### ISSUE TITLE
Running from source

### ISSUE THREAD

**Issue by bgovi** [avallete/ag-grid-autocomplete-editor#33]
I am unable to import the cell editor from the source. It works perfectly fine when using npm install, but when I follow the same instructions after dowloading the package from git it does not work. Is there some preprocessing I have to do first?

**Comment by avallete** [comment]
Depending if you using it with a Typescript project it should work without any preprocessing.

If you using it with a plain javascript, you probably need to run `npm build` first, to transpile all the .ts to .js.

**Comment by bgovi** [comment]
I did an npm install follow by the npm run build. It gives me this error when trying to import the module.

**Comment by bgovi** [comment]
If my path is './ag-grid-autocomplete-editor' 
I get 
"export" AutocompleteSelectelEditor was not found in './ag-grid-autocomplete-editor'

**Comment by avallete** [comment]
If that's the exact error message you get, It look like you simply misspelled the name of the class which is:

`AutocompleteSelectCellEditor` and not `AutocompleteSelectelEditor`

**Comment by bgovi** [comment]
I misspeled the error mesage because i was having issues copying and pasting from terminal.

I use AutocompleteSelectCellEditor

Its the same from your example code. All I did was change the import path to the source code path

**Comment by avallete** [comment]
Just invited you to a chat session on https://gitter.im/ag-grid-autocomplete-editor/community#

It will be more convenient than issue to debug your issue.
