### ISSUE TITLE
Modify the webpack.prod.js file to remove eval() from production bundles

### ISSUE THREAD

**Issue by georgewilli-am** [avallete/ag-grid-autocomplete-editor#43]
Hi, we're experiencing a CSP issue with this package due to the use of eval for sourcemaps in the production bundle, is it possible to remove the use of eval for the production bundles, or perhaps introduce a third bundle that is for use in production without sourcemaps.

Happy to produce a PR the third option or remove it from the production bundle entirely, but thought I'd check with you as to what you'd prefer.

There's some information on how to do this in the ticket below if interested
https://github.com/webpack/webpack/issues/6461

**Comment by avallete** [comment]
You made a good point.

The main reason that I added sourcemaps to the production bundles is to allow to track down error when this package is used as dependency into another project on development.

Looking back on this, I'm not sure it's a good practice to ship them with production bundle, specially with the 'devtool: cheap-module-eval-source-map' which according to [webpack doc](https://webpack.js.org/configuration/devtool/) it's meant to be use in development only.

For what I've understood from the doc, and my quick tests, changing the 'devtool' field to 'source-map', may fix your issue without losing the desired behaviour. Does it sound good to you ?

**Comment by georgewilli-am** [comment]
Yes, that works! Let me know if you'd like me to make the change!

**Comment by avallete** [comment]
Thank's no need to. Since the change is really easy to do.

I've published the new prod bundled version without eval on npm registry, v1.2.6 of the package.

**Comment by georgewilli-am** [comment]
Great, thank you!
