### ISSUE TITLE
¿Accept promises in selectData?

### ISSUE THREAD

**Issue by lcavero** [avallete/ag-grid-autocomplete-editor#46]
It would be great allow put promises in selectData. So you can use cellEditorParams to provide de data based in other selected cell. 
Ty

**Comment by avallete** [comment]
Hi @lcavero ,

Did you try to use the `fetch` option to asynchronously provide data to your select fields as stated into the documentation and the examples:

https://github.com/avallete/ag-grid-autocomplete-editor#autocompletion-with-ajax-request

If it doesn't fill your need, could you elaborate a little more maybe with an use case where using a Promise into `selectData` will be an improvement compared to the actual behaviour ?

**Comment by lcavero** [comment]
Yes, fetch solves my problem.
I close that issue.
Thanks.
