### ISSUE TITLE
version requirement? angular/ag-grid

### ISSUE THREAD

**Issue by hbthanki** [avallete/ag-grid-autocomplete-editor#52]
Hi,

I am using this editor with angular v5.x and ag-grid v22.x.
When I type in the text input, I do not see options as drop down but if I enter the value that is in the selectedData array, it accepts and shows the value.
Is there any version requirement for my case specifically to get the autocompleter to show matching values?

Thanks
H.

**Comment by avallete** [comment]
I don't think so. Into the demo, it run using ag-grid v22.

Maybe you have some CSS who colliding with the CSS of the autocomplete dropdown.

If you could setup a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example) on [StackBlitz](https://stackblitz.com) or other, I would be able to help you.

PS: I did use this plugin with the Vue.js version of ag-grid without troubles.

**Comment by hbthanki** [comment]
I suspected  it. Although, I thought I am wrong and style should work out of the box !
Nevertheless, I have copied css (node_modules\ag-grid-autocomplete-editor\main.css) and put it on app level style and it worked.
