### ISSUE TITLE
Use modules to allow for tree shaking?

### ISSUE THREAD

**Issue by rrajewski** [avallete/ag-grid-autocomplete-editor#54]
Can or should this depend on '@ag-grid-community' instead of 'ag-grid-community'? I'm in the process of upgrading from ag-grid 21... to 22.1.2. When using the new module based packages, my bundle now includes '@angular-grid-community' and what seems like the same ag-grid files under the ag-grid-autocomplete-editor.

![image](https://user-images.githubusercontent.com/3542486/72473273-f0f8e480-37ab-11ea-862a-70c971a509a8.png)

https://www.ag-grid.com/javascript-grid-modules-building/

**Comment by avallete** [comment]
Look good to me.

Thank you for the PR ;)
