### ISSUE TITLE
How to get affected row data after select from autocomplete?

### ISSUE THREAD

**Issue by aguskianto** [avallete/ag-grid-autocomplete-editor#56]
I use your ag-grid-autocomplete-editor and I don't find a way to get whole data for the row affected. I've been using fetch function and I can't get the data on the affected row.

Is there a way to get affected row with the updated data?

**Comment by hbthanki** [comment]
Although, this question is not related to autocomplete, try `valueFormatter` for colDef. It is a function accepting param. check that `param.data`.
