### ISSUE TITLE
If the autocomplete suggestions box can't fit to bottom it jumps to top of the page

### ISSUE THREAD

**Issue by mikkovor** [avallete/ag-grid-autocomplete-editor#63]
So it works fine when the suggestion box fits to the bottom of the screen like this:

![Fits](https://user-images.githubusercontent.com/43668612/80216251-7101d680-8646-11ea-8d6c-9ce77b17ed26.PNG)

And it jumps to the top of the page if doesn't fit like this:

![DoesntFit](https://user-images.githubusercontent.com/43668612/80216312-87a82d80-8646-11ea-8afb-ae9ce41fe13d.PNG)

How to fix this thing?

**Comment by avallete** [comment]
Hi,

It isn't clear to me what your issue really is (event with the provided images, all the blacking make it unclear to me).

But if you have an issue regarding the default styling, you may want to leverage the `customize` parameter, who will allow you to fully customize the style of both, the suggestion box and the input field.

If it doesn't help you, reopen the issue with a minimal reproducible example, or clearer pictures to help me understand the issue precisely.
