### ISSUE TITLE
conditionally render in cell editor is not working with ag-grid autocomplete

### ISSUE THREAD

**Issue by ajayupreti** [avallete/ag-grid-autocomplete-editor#64]
**conditionally render in cell editor is not working with ag-grid autocomplete** 
In the below example I am using two types of cell editor select & normal text editor.
Select editor is rendered when **(params.data.contextValueTypeName === "Select")** else normal text editor is rendered.
But when I am using **AutocompleteSelectCellEditor** in place of select editor it is giving some error.

```
columnDefs: [
        {
          headerName: "Value",
          field: "valueField",
          editable: true,
          cellEditorSelector: params => {
            if (params.data.contextValueTypeName === "Select") {
              return {
                component: "agRichSelectCellEditor",
                params: {
                  values: params.data.listItems
                }
              };
            }
            return null;
          }
]
```
![autocomplete](https://user-images.githubusercontent.com/28973795/80862563-aab08e00-8c93-11ea-993e-9c4072648ba0.PNG)

**Comment by avallete** [comment]
Hi there !

If you want to reference ag-grid components that way (with string name) according to [ag-grid documentation](https://www.ag-grid.com/javascript-grid-components/#registering-framework-components) you have to register it into your gridOptions first.

Something like so:

```js
import {AutocompleteSelectCellEditor} from 'ag-grid-autocomplete-editor';
import {Grid} from 'ag-grid-community';

const gridOptions = {
    columnDefs: columnDefs,
    rowData: rowDatas,
    suppressScrollOnNewData: false,
    components: {
      // Register component into agGrid
      agGridAutocompleteSelectEditor: AutocompleteSelectCellEditor,
    }
};
...

const columnDefs = [
    {
        headerName: "Already present data selector",
        field: "make",
        cellEditorSelector: (params) => {
              return {
                // Use component by string name
                component: "agGridAutocompleteSelectEditor",
                params: {
                  required: true,
                  selectData: selectData,
                  placeholder: 'Select an option',
                }
              };
        },
        ...
    },
];
```

I made a little example for your use case [here](https://stackblitz.com/edit/ag-grid-autocomplete-editor-issue-64).
