### ISSUE TITLE
Missing files in latest release

### ISSUE THREAD

**Issue by faintpixel** [avallete/ag-grid-autocomplete-editor#76]
Getting this error when i try running my app with the latest version:

> ERROR in node_modules/ag-grid-autocomplete-editor/ag-grid-autocomplete-editor.d.ts:3:48 - error TS2307: Cannot find module './autocompleter/autocomplete' or its corresponding type declarations.
> 
> 3 import { AutocompleteItem, EventTrigger } from './autocompleter/autocomplete';

If I grab the autocompleter folder from v1.4.0 and copy it to the folder it works, but it seems like that folder isn't being included anymore.

Thanks for the great package, and sorry if it's just me doing something weird!

**Comment by baloniet** [comment]
> Getting this error when i try running my app with the latest version:
> 
> > ERROR in node_modules/ag-grid-autocomplete-editor/ag-grid-autocomplete-editor.d.ts:3:48 - error TS2307: Cannot find module './autocompleter/autocomplete' or its corresponding type declarations.
> > 3 import { AutocompleteItem, EventTrigger } from './autocompleter/autocomplete';
> 
> If I grab the autocompleter folder from v1.4.0 and copy it to the folder it works, but it seems like that folder isn't being included anymore.
> 
> Thanks for the great package, and sorry if it's just me doing something weird!

Same with me.

**Comment by avallete** [comment]
Thank's for opening this issue, I'm investigating right now I'll try to push a fix before the end of the day.
