### ISSUE TITLE
Should it not show all options on click?

### ISSUE THREAD

**Issue by mohammadali95** [avallete/ag-grid-autocomplete-editor#79]
Hey. Great job on this. I was wondering if clicking on the cell could should all the values and then filter upon typing would be better user experience? 
Also, would this package be compatible with ag-grid-vue? 

Thank you for your help!

**Comment by avallete** [comment]
Hi,

You can achieve this behaviour by overriding two of the default options:

```
cellEditorParams: {
            ...
            autocomplete: {
              showOnFocus: true,
              minLength: 0,
            }
}
```

With the `showOnFocus`, the options will all appear on when starting edition. And set `minLength` to 0 is to avoid the options to close if you hit 'delete' when there is no input in the search box.


About ag-grid-vue, this package has been made to be framework agnostic (angular/react/vue/...). I did use it with ag-grid-vue without issues, you will just have to bind the callback function to whatever you have into your Vue app (ex: dispatch vuex action when a value has been validated, ...)
