### ISSUE TITLE
Feature Request: Batch rendering for autocomplete for large set of data

### ISSUE THREAD

**Issue by bgovi** [avallete/ag-grid-autocomplete-editor#82]
If the list has more than about 500 entries the rendering hangs (It will eventual show up, but a bit laggy). Large drop downs often happen when dealing with lists of people. Is it possible to render in groups. Like only showing the first hundred then more will be rendered if the user scrolls down near bottom.

**Comment by avallete** [comment]
Not sure to totally understand the request here, the 500+ entries is before or after the 'filtering' part of the auto-completion ?

If you have 500+ results on an 'autocomplete search', does implementing a 'infinite scrolling' logic to handle very big matching results is really worthy when, I think, most of the users will type other letters into the search text field to narrow down the possibility, and probably very few will start scrolling into the 500+ list.

Couldn't that situation may be handled into the `fetch` attribute to limit the numbers of results to a pre-determined acceptable numbers for your use case and trim off the rest of the results ?

Maybe setting up the `minLength` attribute to an higher value may help as well.

**Comment by bgovi** [comment]
Yeah. The max out probably makes sense. Thanks.
