### ISSUE TITLE
support for ag-grid 25 and typescript

### ISSUE THREAD

**Issue by DimitarChristoff** [avallete/ag-grid-autocomplete-editor#90]
There seem to be some typescript issues with `AutoCompleteSellectCellEditor` - property `gridOptionsWrapper` is private but not in type `PopupComponent` which it extends 

```
ERROR in C:\dev\ag-grid-autocomplete-editor\ag-grid-autocomplete-editor.ts
./ag-grid-autocomplete-editor.ts
[tsl] ERROR in C:\dev\ag-grid-autocomplete-editor\ag-grid-autocomplete-editor.ts(76,46)
      TS2416: Property 'gridOptionsWrapper' in type 'AutocompleteSelectCellEditor' is not assignable to the same property in base type 'PopupComponent'.
  Type 'GridOptionsWrapper | undefined' is not assignable to type 'GridOptionsWrapper'.
    Type 'undefined' is not assignable to type 'GridOptionsWrapper'.
```

**Comment by avallete** [comment]
Error come from this breaking change: https://github.com/ag-grid/ag-grid/blame/53059eb7f771d8c7268a4cd7e070694e8a2a34d9/community-modules/core/src/ts/context/beanStub.ts#L27

gridOptionsWrapper has been moved to beanStubs, which is extended by Component, so we don't need to declare it into the cellEditor anymore.

Juste removing gridOptionsWrapper from the declarations should work. I'll release a fix ASAP.
