### ISSUE TITLE
Property 'gridOptionsWrapper' is private in type 'AutocompleteSelectCellEditor' but not in type 'PopupComponent'.

### ISSUE THREAD

**Issue by Amritha-Nambi** [avallete/ag-grid-autocomplete-editor#91]
I installed the package and tried to use it. I am getting this error 
"Property 'gridOptionsWrapper' is private in type 'AutocompleteSelectCellEditor' but not in type 'PopupComponent'.". 

Can anyone help me with this?

**Comment by avallete** [comment]
Duplication of #90

Some breaking changes has been introduced in latests ag-grid vesion. I need to fix this when I have some time.

In the meantime, you can downgrade ag-grid v23.2.1 should resolve this issue. I'll try to fix that issue before next week-end.

**Comment by shahggeek** [comment]
I was facing same issue with v24.0 of ag-grid, I guess fix is to remove "private gridOptionsWrapper" field from AutoCompleteSelectCellEditor class. Not sure if its correct way to fix, but it works on local. Please keep us posted when new version is ready with this change.
